kegiatanku/urls.py
from django.urls import path
from . import views

app_name = 'kegiatanku'

urlpatterns = [
    path('', views.index, name='index'),
    path('tambah/', views.tambahAstaga, name='tambah'),
    path('tambahKegiatan/', views.tambahKegiatan, name='tambahKegiatan')
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kegiatanku.urls'))
]

kegiatanku/models.py
from django.db import models
from django.db.models.deletion import SET_NULL

# Create your models here.
class peserta(models.Model):
    nama = models.CharField(max_length=50, null=True)
    domisili = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.nama

class tags(models.Model):
    peserta_kegiatan = models.ForeignKey(peserta, null=True, on_delete=models.SET_NULL)
    nama_kegiatan = models.CharField(max_length=100, null=True)
    deskripsi = models.CharField(max_length=500, null=True)
    
    def __str__(self):
        return self.nama_kegiatan

kegiatanku/forms.py
from django.forms import ModelForm
from .models import peserta, tags

class tambahOrang(ModelForm):
    class Meta:
        model = peserta
        fields = '__all__'

class tambahTag(ModelForm):
    class Meta:
        model = tags
        fields = '__all__'

kegiatanku/views.py
from .forms import tambahOrang, tambahTag
from django.shortcuts import render, redirect
from .models import *

# Create your views here.
def index(request):
    orang = tags.objects.all()
    return render(request, 'kegiatanku/index.html', {'orang':orang})

def tambahAstaga(request):
    form = tambahOrang()

    if request.method == 'POST':
        form = tambahOrang(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")

    context = {'form':form}
    return render(request, 'kegiatanku/form.html', context)

def tambahKegiatan(request):
    form = tambahTag()

    if request.method == 'POST':
        form = tambahTag(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    
    context = {'form':form}
    return render(request, 'kegiatanku/kegiatan.html', context)

    

kegiatanku/templates/kegiatanku/form.html
<!DOCTYPE html>
<html>
    <head>
        <title>Isi Data :D</title>
    </head>
        
    <body>
        <form action="" method="POST">
            <table class="table">
                <tbody>
                    {{ form.as_table }}
                    <tr>
                        <th></th>
                        <td>
                            {% csrf_token %}
                            <button class="btn btn-outline-primary" type="submit" name="Simpan">Simpan</button>
                            <a class="btn btn-outline-danger" href="{% url 'kegiatanku:index'%}" name="Cancel">Batal</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </body>
</html>

kegiatanku/templates/kegiatanku/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Kegiatanku</title>
    </head>

    <body>
        <h1>Responden</h1>
        <table border="solid">
            <tr>
                <th>Responden</th>
                <th>Domisili</th>
                <th>Kegiatan</th>
            </tr>
            {% for i in orang %}
            <tr>
                <td>{{i.peserta_kegiatan.nama}}</td>
                <td>{{i.peserta_kegiatan.domisili}}</td>
                <td>{{i.nama_kegiatan}}</td>
            </tr>
            {% endfor %}
        </table>

        <a href="{% url 'kegiatanku:tambah' %}">Tambah Peserta</a>
        <a href="{% url 'kegiatanku:tambahKegiatan' %}">Tambah Kegiatan</a>
    </body>
</html>

kegiatanku/templates/kegiatanku/kegiatan.html
<!DOCTYPE html>
<html>
    <head>
        <title>Isi Data :D</title>
    </head>
        
    <body>
        <form action="" method="POST">
            <table class="table">
                <tbody>
                    {{ form.as_table }}
                    <tr>
                        <th></th>
                        <td>
                            {% csrf_token %}
                            <button class="btn btn-outline-primary" type="submit" name="Simpan">Simpan</button>
                            <a class="btn btn-outline-danger" href="{% url 'kegiatanku:index'%}" name="Cancel">Batal</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </body>
</html>